(function(root) {
  "use strict";
  const D=root.PULSO_DATA, E=root.PulsoEngine;
  const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const n=(x,d=2)=>D.displayNumber(x,d);
  const usd=x=>"US$ "+n(x*1e9);
  const row=(label,value)=>"<dt>"+esc(label)+"</dt><dd>"+value+"</dd>";
  const table=(headers,rows)=>'<div class="table-wrap"><table><thead><tr>'+headers.map(h=>"<th>"+esc(h)+"</th>").join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+r.map(v=>"<td>"+v+"</td>").join("")+"</tr>").join("")+"</tbody></table></div>";
  const detail=(title,body)=>"<details><summary>"+esc(title)+"</summary>"+body+"</details>";
  const list=rows=>'<dl class="start-facts">'+rows.map(r=>row(...r)).join("")+"</dl>";
  const labels={efficiency:"Eficiencia",industry:"Industria",welfare:"Bienestar",volatility:"Volatilidad",diplomacy:"Diplomacia",education:"Educación",infrastructure:"Infraestructura",green:"Ambiente",growth:"Crecimiento",stability:"Estabilidad",trade:"Comercio",agriculture:"Agro",security:"Seguridad",technology:"Tecnología",health:"Salud",tourism:"Turismo",energy:"Energía"};
  function leader(figure) {
    return '<details class="leader-modifiers"><summary>Rasgos de esta selección</summary><p>Modificadores del escenario hipotético; no son una evaluación de la persona real ni porcentajes garantizados de resultados.</p>'+
      list(Object.entries(figure.bonuses||{}).map(([k,v])=>[labels[k]||k,(v>0?"+":"")+n(v)+" puntos del modelo"]))+"</details>";
  }
  function render(s) {
    const c=s.countries[s.playerCountryId], demo=c.laborSnapshot;
    const owned=D.constructions.filter(b=>(c.buildings[b.id]||0)+(c.privateBuildings[b.id]||0)>0);
    const technologies=D.technologies.filter(t=>c.research.levels[t.id]>0);
    const scratch=c.startingScenario==="scratch";
    const sourceLabels={population:"Población",gdp:"PBI",areaKm2:"Superficie",agricultureKm2:"Superficie agrícola",lifeExpectancy:"Esperanza de vida",unemployment:"Desocupación",railKm:"Ferrocarriles",irrigatedPercent:"Superficie irrigada"};
    let html='<section class="country-dossier" aria-label="Ficha del país"><h3>Antes de gobernar: '+esc(c.name)+'</h3><p>Valores de inicio de la simulación. El mundo no avanza mientras comparás. Las fuentes con año se separan de las estimaciones y reglas de juego; no son datos en tiempo real.</p>';
    html+='<div class="start-summary">'+[
      ["Población",n(c.population*1e6,0)],["Reservas",usd(c.reserves)],["Deuda",usd(E.debtTotal(c))],
      ["PBI anual de referencia",usd(c.gdp)],["Desocupación",n(c.unemployment)+"%"],
      ["Tecnologías conocidas",technologies.length+" / "+D.technologies.length],
      ["Tipos de instalaciones",owned.length],["Superficie",n(c.land.areaKm2)+" km²"]
    ].map(([k,v])=>"<article><small>"+k+"</small><strong>"+v+"</strong></article>").join("")+"</div>";
    if(scratch) html+='<p class="start-warning"><strong>Desafío desde cero:</strong> sin viviendas, puestos de trabajo, ejército, industria ni investigaciones. Se conservan población, educación de los habitantes, territorio, caja y deuda. El PBI es la referencia heredada, no una producción garantizada: se ajustará con la actividad. Los 500.000.000 de granos están en una reserva extraordinaria de escenario, sin huella territorial adicional, que no puede reconstruirse. No se venden automáticamente al inicio; la ayuda alimentaria está activada. El consumo y el deterioro reducen el stock.</p>';
    html+=detail("Población, bienestar y territorio",list([
      ["Región",esc(c.region)],["Sistema político",esc(c.politicalSystem)],["Moneda de referencia",esc(c.currency)],["Menores de 18",n(demo.children*1e6,0)],["Personas en edad laboral",n(demo.workingAge*1e6,0)],["Ocupados",n(demo.employed*1e6,0)],["Desocupados",n(demo.unemployed*1e6,0)],["Jubilados / edad previsional",n(demo.retired*1e6,0)],["Edad laboral",c.workPolicy.start+" a "+c.workPolicy.retire+" años"],["Esperanza de vida",n(c.lifeExpectancy)+" años"],["Natalidad",n(c.birthRate)+"‰ anual"],["Felicidad",n(c.happiness)+"/100"],["Educación",n(c.education)+"/100"],["Salud",n(c.health)+"/100"],["Estabilidad",n(c.stability)+"/100"],["Apoyo",n(c.popularity)+"/100"],["Viviendas nuevas / normales / a refaccionar",Object.values(c.housingStock).map(v=>n(v*1e6,0)).join(" / ")],["Vivienda adecuada",n(c.housing)+"%"],["Hectáreas agrícolas / irrigadas",n(c.land.agricultureHa)+" / "+n(c.land.irrigatedHa)],["Suelo residencial / industrial",n(c.land.residentialHa)+" / "+n(c.land.industrialHa)+" ha"],["Suelo restringido",n(c.land.restrictedHa)+" ha"],["Turismo anual de referencia",n(c.tourism*1e6,0)]
    ]));
    const taxes={vat:"IVA",income:"Ganancias",inheritance:"Herencias",imports:"Importaciones",exports:"Exportaciones"};
    html+=detail("Economía, impuestos y compromisos",list([
      ["PBI por habitante",usd(c.gdp/Math.max(1,c.population*1e6))],["Inflación",n(c.inflation)+"%"],["Deuda / PBI",n(E.debtTotal(c)/c.gdp*100)+"%"],["Caja privada / hogares",usd(c.finance.privateCash)+" / "+usd(c.finance.householdCash)],["Pensión mensual por jubilado","US$ "+n(c.pensionPolicy.monthlyUsd)],["Crédito automático",c.finance.automaticCredit?"Activado":"Desactivado"],...Object.entries(taxes).map(([id,label])=>[label,n(c.taxes[id])+"%"])
    ])+"<p>La recaudación y el balance efectivo se calculan cuando ocurren las operaciones. El PBI y los stocks no son dinero disponible para gastar.</p>");
    html+=detail("Fuentes primarias inagotables y depósitos",table(["Fuente","Cuota máxima mensual","Condición"],Object.entries(c.primaryEndowment).map(([id,q])=>[esc(D.getMaterial(id).label),n(q,8)+" "+esc(D.getMaterial(id).unit),"Fija e inagotable; necesita espacio"]))+"<p>Las cuotas no requieren edificios ni investigación. La extracción industrial adicional exige instalaciones, tecnología y depósitos finitos.</p>"+table(["Depósito finito","Terrestre","Marítimo"],Object.entries(c.naturalDeposits).map(([id,d])=>[esc(D.getMaterial(id).label),n(d.land)+" "+esc(D.getMaterial(id).unit),n(d.sea)+" "+esc(D.getMaterial(id).unit)])));
    html+=detail("Todos los recursos, inventarios y comercio",table(["Recurso / unidad","Stock público","Stock privado","Almacén público / privado","Capacidad productiva mensual teórica","Necesidad mensual inicial","Venta automática","Importación automática"],D.materials.map(m=>{const r=E.resourceReport(s,m.id);return [esc(m.label)+" ("+esc(m.unit)+")",n(c.publicStocks[m.id],8),n(c.privateStocks[m.id],8),n(r.storage.public,8)+" / "+n(r.storage.private,8),n(r.capacity,8),n(c.needs[m.id],8),c.tradePolicies[m.id].sell?"Sí":"No",c.tradePolicies[m.id].autoImport?"Sí":"No"];}))+"<p>El modo desde cero dispone de un patio temporal vacío para recibir los insumos de un laboratorio; no otorga materiales ni plantas. Cada recurso muestra los requisitos de producción dentro de la partida.</p>");
    html+=detail("Edificios, infraestructura y empleos",table(["Instalación","Módulos públicos","Módulos privados","Capacidad física por módulo"],owned.map(b=>[esc(b.label),n(c.buildings[b.id],8),n(c.privateBuildings[b.id],8),b.storageFor?n(b.storageAmount)+" "+esc(D.getMaterial(b.storageFor).unit):n(b.quantity||1)+" "+esc(b.unit||"instalaciones")]))+table(["Ministerio","Funcionarios","Empleados privados","Sueldo público mensual"],D.sectors.map(sec=>[esc(sec.label),n(c.sectors[sec.id].publicWorkers,0),n(c.sectors[sec.id].privateWorkers,0),"US$ "+n(c.sectors[sec.id].salary)]))+"<p>Las instalaciones heredadas pueden expresarse como módulos equivalentes fraccionarios.</p>");
    html+=detail("Investigaciones y ruta de desarrollo",table(["Tecnología","Nivel","Estado / requisitos","Desbloquea construcciones"],D.technologies.map(t=>[esc(t.label),c.research.levels[t.id]||0,c.research.levels[t.id]?"Investigada":t.requires.some(id=>!c.research.levels[id])?"Faltan: "+t.requires.filter(id=>!c.research.levels[id]).map(id=>esc(D.getTechnology(id).label)).join(", "):"Disponible para investigar",t.unlockBuildings.map(id=>esc(D.getBuilding(id).label)).join(", ")||"Mejora sectorial"]))+(scratch?"<p><strong>Cómo empezar:</strong> financiá el primer laboratorio con reservas, ventas o crédito. Comprá sus insumos, construí desde Educación y asigná funcionarios a Ciencia avanzada con presupuesto. En este modo el laboratorio no exige Universidades; las demás construcciones mantienen sus requisitos.</p>":""));
    html+=detail("Ejército, relaciones y energía",list([["Soldados / formados",n(c.military.soldiers,0)+" / "+n(c.military.trained,0)],["Capacidad militar",n(E.militaryCapacity(c),0)],["Sueldo mensual por soldado","US$ "+n(c.military.salary)],["Bases navales",n(c.buildings.naval_base)],["Demanda eléctrica anual de referencia",n(c.electricityDemandTWh)+" TWh"],["Generación eléctrica anual de referencia",n(c.electricityGenerationTWh)+" TWh"]])+table(["País","Relación /100"],Object.values(s.countries).filter(x=>x.id!==c.id).sort((a,b)=>a.name.localeCompare(b.name,"es")).map(x=>[esc(x.name),n(E.relationScore(c,x))])));
    html+=detail("Fuentes y años de referencia",table(["Indicador","Valor de fuente","Año","Código de fuente"],Object.entries(c.dataSources||{}).map(([id,f])=>[esc(sourceLabels[id]||id),n(f.value),esc(f.year||"Sin año"),esc(f.source||"Escenario")]))+"<p>Las cifras no incluidas aquí y los ajustes de territorio, capacidades, población inicial y figuras son parte del escenario. Consultá FUENTES.md para procedencia y límites. La ficha muestra los valores efectivos del juego.</p>");
    return html+"</section>";
  }
  root.PulsoStartPreview={render,leader};
})(window);
