import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createHash } from "node:crypto";
import { validateCatalog } from "../src/catalog-schema.js";
export const TABS = {
  vehicles: "Vehiculos",
  parts: "Repuestos",
  drivers: "Pilotos",
  mechanics: "Mecanicos",
  races: "Carreras",
  prizes: "Premios",
  settings: "Ajustes",
};
const numeric = new Set([
  "price",
  "stock",
  "condition",
  "salary",
  "efficiency",
  "round",
  "startDay",
  "prizeFactor",
  "position",
  "points",
  "race",
  "championship",
  "value",
]);
export function parseCSV(input) {
  const rows = [];
  let row = [],
    cell = "",
    quoted = false;
  const text = input.replace(/^\uFEFF/, "");
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === '"') {
      if (quoted && text[i + 1] === '"') ((cell += '"'), i++);
      else quoted = !quoted;
    } else if (ch === "," && !quoted) {
      row.push(cell);
      cell = "";
    } else if ((ch === "\n" || ch === "\r") && !quoted) {
      if (ch === "\r" && text[i + 1] === "\n") i++;
      row.push(cell);
      if (row.some((v) => v !== "")) rows.push(row);
      row = [];
      cell = "";
    } else cell += ch;
  }
  if (quoted) throw Error("CSV con comillas sin cerrar.");
  if (cell || row.length) {
    row.push(cell);
    rows.push(row);
  }
  if (!rows.length) throw Error("CSV vacío.");
  const headers = rows.shift().map((h) => h.trim());
  if (
    new Set(headers).size !== headers.length ||
    headers.some(
      (h) => !h || ["__proto__", "constructor", "prototype"].includes(h),
    )
  )
    throw Error("Encabezados CSV inválidos.");
  return rows.map((cells, i) => {
    if (cells.length !== headers.length)
      throw Error(`CSV fila ${i + 2}: cantidad incorrecta de columnas.`);
    return Object.fromEntries(
      headers.map((h, j) => {
        let v = cells[j].trim();
        if (numeric.has(h)) {
          if (!/^-?\d+(?:[.,]\d+)?$/.test(v))
            throw Error(
              `Número inválido en ${h}, fila ${i + 2}. Usá valores sin separador de miles.`,
            );
          v = Number(v.replace(",", "."));
        } else if (h === "available") {
          if (!/^(true|false|verdadero|falso|1|0)$/i.test(v))
            throw Error("Disponibilidad inválida.");
          v = /^(true|verdadero|1)$/i.test(v);
        }
        return [h, v];
      }),
    );
  });
}
export async function buildCatalog(readTab) {
  const catalog = { schemaVersion: 1, revision: "pending" };
  const results = await Promise.all(
    Object.entries(TABS).map(async ([key, name]) => [
      key,
      parseCSV(await readTab(key, name)),
    ]),
  );
  for (const [key, rows] of results) catalog[key] = rows;
  catalog.races.sort((a, b) => a.round - b.round);
  catalog.prizes.sort((a, b) => a.position - b.position);
  catalog.revision = createHash("sha256")
    .update(JSON.stringify({ ...catalog, revision: "" }))
    .digest("hex")
    .slice(0, 16);
  return validateCatalog(catalog);
}
export async function sync({
  sourceDir,
  outputDir = "data",
  configPath = "config/sheets.json",
  check = false,
} = {}) {
  const config = sourceDir
    ? null
    : JSON.parse(await fs.readFile(configPath, "utf8"));
  if (config && !config.enabled)
    throw Error(
      "La conexión real de Google Sheets está pendiente. Configurá config/sheets.json después de crear las hojas.",
    );
  const catalog = await buildCatalog(async (key, name) => {
    if (sourceDir)
      return fs.readFile(path.join(sourceDir, `${name}.csv`), "utf8");
    const url = new URL(config.csvUrls[key]);
    if (
      url.protocol !== "https:" ||
      url.hostname !== "docs.google.com" ||
      !url.pathname.startsWith("/spreadsheets/")
    )
      throw Error(`URL de Sheets inválida: ${name}`);
    const response = await fetch(url, { signal: AbortSignal.timeout(30000) });
    if (!response.ok) throw Error(`${name}: HTTP ${response.status}`);
    const text = await response.text();
    if (text.length > 2000000 || /^\s*</.test(text))
      throw Error(`${name}: respuesta no CSV o demasiado grande.`);
    return text;
  });
  if (!check) {
    await fs.mkdir(outputDir, { recursive: true });
    const json = JSON.stringify(catalog, null, 2);
    await fs.writeFile(path.join(outputDir, "catalog.json"), json + "\n");
    await fs.writeFile(
      path.join(outputDir, "catalog.js"),
      "// Generated by scripts/sync-catalog.mjs. Edit the spreadsheet catalog.\nexport const CATALOG = " +
        json +
        ";\n",
    );
  }
  return catalog;
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const value = (flag) => {
    const i = process.argv.indexOf(flag);
    return i < 0 ? undefined : process.argv[i + 1];
  };
  try {
    const c = await sync({
      sourceDir: value("--source-dir"),
      outputDir: value("--output-dir"),
      check: process.argv.includes("--check"),
    });
    console.log(
      `Catálogo verificado: ${c.revision} · ${c.vehicles.length} vehículos · ${c.parts.length} repuestos · ${c.races.length} carreras`,
    );
  } catch (e) {
    console.error(e.message);
    process.exitCode = 1;
  }
}
