'use client';
import { useState } from 'react';import { Compass, X, ArrowRight, ArrowDownToLine, ChartNoAxesCombined, Trophy } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose } from './ui/dialog';import { Button } from './ui/button';import { Input } from './ui/input';import { NativeSelect } from './ui/native-select';
import { CITIES,EVENTS } from '@/lib/catalog';import { quarterLabel,type Game } from '@/lib/engine';import { money,number,percent } from '@/lib/format';
export function GameDialog({modal,close,game,download,create}:{modal:'new'|'help'|'report'|null;close:()=>void;game:Game;download:()=>void;create:(name:string,hub:string)=>void}){
 const [name,setName]=useState(''),[hub,setHub]=useState('EZE');const last=game.history.at(-1),event=EVENTS[game.event];
 return <Dialog open={modal!==null} onOpenChange={open=>{if(!open)close();}}><DialogContent className="game-dialog" showCloseButton={false}><DialogClose render={<Button variant="ghost" size="icon" className="dialog-x" aria-label="Cerrar ventana"/>}><X/></DialogClose>
 {modal==='new'&&<><span className="dialog-icon"><Compass/></span><DialogTitle>El próximo capítulo empieza con vos.</DialogTitle><DialogDescription>Creá una aerolínea en 2026 con US$ 240 millones y una flota por construir.</DialogDescription><form onSubmit={e=>{e.preventDefault();create(name,hub);}}><label className="field-label" htmlFor="airline-name">Nombre de la aerolínea</label><Input id="airline-name" required maxLength={30} value={name} onChange={e=>setName(e.target.value)} placeholder="Por ejemplo, Horizonte Air"/><label className="field-label" htmlFor="new-hub">Aeropuerto base</label><NativeSelect id="new-hub" className="full-select" value={hub} onChange={e=>setHub(e.target.value)}>{CITIES.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</NativeSelect><div className="planner-tip">Esta acción reemplaza la partida activa. Podés descargar una copia antes de continuar.</div><Button type="button" variant="outline" className="full-button" onClick={download}><ArrowDownToLine/> Descargar partida actual</Button><Button type="submit" className="primary-button full-button" disabled={!name.trim()}>Crear aerolínea <ArrowRight/></Button></form></>}
 {modal==='help'&&<><span className="dialog-icon"><Compass/></span><DialogTitle>De una conexión a una gran aerolínea.</DialogTitle><DialogDescription>Objetivo: operar 8 rutas y cerrar un trimestre con ganancias. Después podés seguir expandiéndote.</DialogDescription><ol className="how-to">{[['Construí tu flota','Comprá aviones en Mi flota. Cada uno opera una ruta y tiene un alcance máximo.'],['Encontrá una buena conexión','Elegí un destino, asigná un avión y ajustá tarifa y frecuencias. Una frecuencia es un viaje de ida y vuelta por semana.'],['Miralo desde los números','La proyección combina demanda, competencia, reputación y costos. Subir la tarifa puede dejar asientos vacíos. Los aviones ociosos también pagan mantenimiento.'],['Avanzá y volvé a decidir','Cada turno dura 13 semanas. Los ingresos se cobran al cerrar. Revisá el nuevo evento antes de expandirte. Si el capital queda negativo, termina la partida.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="planner-tip">La partida inicial trae dos rutas desde Buenos Aires para explorar el juego. En Nueva aerolínea podés elegir nombre y base y empezar desde cero.</div><p className="field-hint">Modelos y ciudades reales; precios, demanda y rivales simulados. Cartografía: <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a>.</p><Button className="primary-button full-button" onClick={close}>Volver a mi aerolínea <ArrowRight/></Button></>}
 {modal==='report'&&last&&<><span className="dialog-icon">{game.won?<Trophy/>:<ChartNoAxesCombined/>}</span><p className="eyebrow">INFORME · {quarterLabel(last.turn)}</p><DialogTitle>{game.bankrupt?'Un cierre difícil.':last.profit>=0?'Un trimestre que suma.':'Es momento de ajustar el rumbo.'}</DialogTitle><DialogDescription>Resultado operativo de {game.name}. Evento del período: {last.event}.</DialogDescription><div className={`report-profit ${last.profit>=0?'positive':'negative'}`}>{money(last.profit)}<small>resultado del trimestre</small></div><div className="report-grid">{[['Ingresos',money(last.revenue)],['Costos',money(last.costs)],['Pasajeros',number(last.passengers)],['Ocupación',percent(last.occupancy)]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="report-next"><p className="eyebrow">PRÓXIMO TRIMESTRE · {quarterLabel(game.turn)}</p><h3>{event.title}</h3><p>{event.text}</p></div>{game.won&&<p className="positive">¡Alcanzaste el objetivo de expansión! Podés seguir jugando.</p>}<Button className="primary-button full-button" onClick={close}>Continuar <ArrowRight/></Button></>}
 </DialogContent></Dialog>;
}
