'use client';
import { useEffect, useRef, useState } from 'react';
import { Compass, Plane, Globe2, ChartNoAxesCombined, ArrowRight, Check, Plus, CircleHelp, X, AlertCircle, CheckCircle2, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { CITIES, city } from '@/lib/catalog';
import { createGame, advanceQuarter, totals, parseSave, quarterLabel, SAVE_KEY, type Game as State } from '@/lib/engine';
import { money } from '@/lib/format';
import { RoutesView } from './routes-view';
import { FleetView, FinanceView } from './management-views';
import { GameDialog } from './game-dialog';
import { registerGameTools } from '@/lib/webmcp';
export type View='routes'|'fleet'|'finances';
export type Act=(fn:(s:State)=>State,message:string)=>boolean;
export default function Game(){
 const [game,setGame]=useState<State>(()=>createGame()); const ref=useRef(game);
 const [ready,setReady]=useState(false),[saveStatus,setSaveStatus]=useState('Cargando partida');const blocked=useRef(false);
 const [view,setView]=useState<View>('routes'),[selected,setSelected]=useState('LIM'),[modal,setModal]=useState<'new'|'help'|'report'|null>(null);
 const [notice,setNotice]=useState<{text:string;error:boolean}|null>(null);const file=useRef<HTMLInputElement>(null);
 function notify(text:string,error=false){setNotice({text,error});}
 function commit(s:State){ref.current=s;setGame(s);}
 const act:Act=(fn,message)=>{try{commit(fn(ref.current));notify(message);return true;}catch(e){notify(e instanceof Error?e.message:'No se pudo completar la operación.',true);return false;}};
 function select(id:string){if(id===ref.current.hub){notify('Esta es tu base. Elegí otro aeropuerto para planificar una ruta.');return;}setSelected(id);setView('routes');}
 function advance(){if(act(advanceQuarter,'Trimestre cerrado.'))setModal('report');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(ref.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`aeronauta-${quarterLabel(ref.current.turn).replace(' ','-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Partida descargada.');}
 async function upload(f?:File){if(!f)return;try{if(f.size>5e6)throw Error('El archivo supera 5 MB.');const s=parseSave(await f.text());blocked.current=false;commit(s);setSelected(CITIES.find(c=>c.id!==s.hub)!.id);setView('routes');notify('Partida recuperada.');}catch(e){notify(e instanceof Error?e.message:'No se pudo abrir la partida.',true);}finally{if(file.current)file.current.value='';}}
 useEffect(()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=parseSave(raw);commit(s);setSelected(CITIES.find(c=>c.id!==s.hub&&!s.routes.some(r=>r.to===c.id))?.id??CITIES.find(c=>c.id!==s.hub)!.id);}}catch{blocked.current=true;setSaveStatus('Guardado anterior protegido');notify('No pude leer la partida guardada. Se conserva intacta. Podés cargar otra partida o crear una nueva.',true);}setReady(true);},[]);
 useEffect(()=>{if(!ready||blocked.current)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(game));setSaveStatus('Partida guardada');}catch{setSaveStatus('Sin guardado automático');}},[game,ready]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),8500);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>registerGameTools(()=>ref.current,commit,()=>setModal('report')),[]);
 const t=totals(game),idle=game.fleet.filter(p=>!game.routes.some(r=>r.plane===p.id)).length;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><Compass/><div>AERONAUTA<small>GESTIÓN DE AEROLÍNEAS</small></div></div><div className="airline-card"><span className="airline-icon"><Plane/></span><div><strong>{game.name}</strong><small>{city(game.hub).name} · {game.hub}</small></div></div><p className="nav-caption">CENTRO DE OPERACIONES</p><nav aria-label="Secciones del juego">{([{id:'routes',name:'Red de rutas',icon:Globe2,count:game.routes.length},{id:'fleet',name:'Mi flota',icon:Plane,count:game.fleet.length},{id:'finances',name:'Finanzas',icon:ChartNoAxesCombined}] as const).map(n=><button key={n.id} className={view===n.id?'active':''} aria-current={view===n.id?'page':undefined} onClick={()=>setView(n.id)}><n.icon/>{n.name}{'count'in n&&<span>{String(n.count).padStart(2,'0')}</span>}</button>)}</nav><div className="sidebar-bottom"><span className="eyebrow">{game.won?'OBJETIVO CUMPLIDO':'TU PRÓXIMO OBJETIVO'}</span><h3>{game.won?'Una red sin fronteras.':'El mundo te espera.'}</h3><p>Operá 8 rutas y cerrá un trimestre con ganancias.</p><Progress className="goal-progress" value={Math.min(100,game.routes.length/8*100)} aria-label="Progreso hacia 8 rutas"/><small>{game.routes.length} de 8 rutas</small><button onClick={()=>setModal('help')}><CircleHelp size={17}/> Cómo jugar</button><button className="new-airline" onClick={()=>setModal('new')}><Plus size={17}/> Nueva aerolínea</button></div></aside>
 <main className="workspace"><header className="topbar"><span><i className="live-dot"/> OPERACIONES · {2026+Math.floor(game.turn/4)}</span><span className="save-state"><Check size={13}/>{saveStatus}<Button variant="ghost" size="icon-sm" className="mobile-help" aria-label="Cómo jugar" onClick={()=>setModal('help')}><CircleHelp/></Button></span></header><div className="main-content"><div className="page-heading"><div><p className="eyebrow">{view==='routes'?'TU CENTRO DE MANDO':view==='fleet'?'EL MOTOR DE TU AEROLÍNEA':'CADA DECISIÓN CUENTA'}</p><h1>{view==='routes'?'Red de operaciones':view==='fleet'?'Tu flota, tu futuro':'Balance de vuelo'}<span>.</span></h1><p>{view==='routes'?'Diseñá conexiones. Encontrá tu próximo destino.':view==='fleet'?'Elegí el avión correcto para cada oportunidad.':'Ingresos, costos y espacio para crecer.'}</p></div><div className="turn-control"><span>{['ENE — MAR','ABR — JUN','JUL — SEP','OCT — DIC'][game.turn%4]}<strong>Trimestre {game.turn%4+1}, {2026+Math.floor(game.turn/4)}</strong></span><Button className="primary-button" disabled={!ready||game.bankrupt} onClick={advance}>Avanzar trimestre <ArrowRight/></Button></div></div>
 {game.bankrupt&&<div className="state-banner error"><AlertCircle/><div><strong>La aerolínea se quedó sin capital.</strong><p>La partida terminó. Revisá el balance y volvé a intentarlo.</p></div><Button onClick={()=>setModal('new')}>Nueva partida</Button></div>}{game.won&&!game.bankrupt&&<div className="state-banner success"><Trophy/><div><strong>¡Objetivo cumplido!</strong><p>Conseguiste 8 rutas y un trimestre rentable. Podés seguir jugando.</p></div></div>}
 <section className="stats-grid" aria-label="Estado de la aerolínea">{[['Capital disponible',money(game.cash),'Saldo después de tus inversiones',''],[view==='fleet'?'Aviones disponibles':'Rutas activas',String(view==='fleet'?idle:game.routes.length).padStart(2,'0'),view==='fleet'?`${game.fleet.length} aviones en la flota`:`${game.routes.length+1} ciudades conectadas`,''],['Resultado previsto',money(t.profit),`Estimación para ${quarterLabel(game.turn)}`,t.profit>=0?'positive':'negative'],['Reputación',`${game.reputation} / 100`,'La rentabilidad mejora tu reputación','']].map(([a,b,c,tone])=><div className="stat" key={a}><span>{a}</span><strong className={tone}>{b}</strong><small>{c}</small></div>)}</section>
 {view==='routes'&&<RoutesView game={game} selected={selected} select={select} act={act} goFleet={()=>setView('fleet')} ready={ready}/>}{view==='fleet'&&<FleetView game={game} act={act} select={select} goRoutes={()=>setView('routes')}/>} {view==='finances'&&<FinanceView game={game} download={download} upload={()=>file.current?.click()} newGame={()=>setModal('new')} report={()=>setModal('report')}/>}
 <footer className="app-footer"><span>AERONAUTA <b>·</b> EDICIÓN 2026 <b>·</b> PROTOTIPO JUGABLE</span><span>Economía simulada · Guardado en este dispositivo</span></footer></div></main><input type="file" ref={file} accept=".json,application/json" hidden onChange={e=>void upload(e.target.files?.[0])}/>
 {notice&&<div className={`toast ${notice.error?'toast-error':''}`} role={notice.error?'alert':'status'}>{notice.error?<AlertCircle/>:<CheckCircle2/>}<span>{notice.text}</span><Button variant="ghost" size="icon-sm" aria-label="Cerrar mensaje" onClick={()=>setNotice(null)}><X/></Button></div>}
 <GameDialog modal={modal} close={()=>setModal(null)} game={game} download={download} create={(name,hub)=>{if(act(()=>createGame(name,hub,false),'¡Tu aerolínea está lista! Comprá el primer avión.')){blocked.current=false;setSelected(CITIES.find(c=>c.id!==hub)!.id);setView('fleet');setModal(null);}}}/></div>;
}
