'use client';
import { Plane, Globe2, Users, Plus, ArrowRight, ArrowUpRight, ChartNoAxesCombined, Building2, ArrowDownToLine, Upload } from 'lucide-react';
import { Button } from './ui/button';import { AIRCRAFT, aircraft, city } from '@/lib/catalog';import { buyPlane, sellPlane, totals, OVERHEAD, quarterLabel, type Game } from '@/lib/engine';import { money,number } from '@/lib/format';import type { Act } from './game';
export function FleetView({game,act,select,goRoutes}:{game:Game;act:Act;select:(id:string)=>void;goRoutes:()=>void}){
 const idle=game.fleet.filter(p=>!game.routes.some(r=>r.plane===p.id)).length;
 return <><div className="section-heading"><div><h2>Tu flota</h2><p>Un avión por ruta. Cerrá una conexión para liberar su aeronave.</p></div><span className="tag">{idle} DISPONIBLES</span></div>{game.fleet.length?<div className="owned-grid">{game.fleet.map(p=>{const m=aircraft(p.model),r=game.routes.find(r=>r.plane===p.id);return <div className="owned-plane" key={p.id}><span className="plane-badge"><Plane/></span><div><h3>{m.name}</h3><p>{p.id.toUpperCase()} · {r?`${game.hub} → ${r.to}`:'Disponible para asignar'}</p></div><span className={`status-pill ${r?'':'idle'}`}>{r?'En operación':'Disponible'}</span><Button variant="ghost" disabled={game.bankrupt} onClick={()=>r?select(r.to):goRoutes()}>{r?'Gestionar ruta':'Abrir ruta'}<ArrowRight/></Button>{!r&&<Button variant="outline" disabled={game.bankrupt} onClick={()=>act(s=>sellPlane(s,p.id),'Avión vendido al 70% del valor de compra.')}>Vender · {money(m.price*.7)}</Button>}</div>;})}</div>:<div className="empty-state compact"><Plane/><h3>Tu primer avión está aquí abajo.</h3><p>Comenzá con un modelo regional para mantener los costos bajo control.</p></div>}
 <div className="section-heading market-heading"><div><p className="eyebrow">UNA FLOTA PARA CADA AMBICIÓN</p><h2>Mercado de aviones</h2><p>Entrega inmediata en esta versión del juego.</p></div><span className="tag">4 MODELOS</span></div><div className="aircraft-market">{AIRCRAFT.map((m,i)=><article key={m.id} className="aircraft-card"><div className={`aircraft-card-top aircraft-tone-${i}`}><span className="tag">{m.family.toUpperCase()}</span><Plane aria-hidden="true" strokeWidth={1}/><span className="aircraft-model-code">{['E195-E2','A320neo','A321XLR','787-9'][i]}</span></div><div className="aircraft-card-body"><h3>{m.name}</h3><p>{m.description}</p><div className="aircraft-specs"><span><Users size={16}/>{m.seats} asientos</span><span><Globe2 size={16}/>{number(m.range)} km</span></div><div className="price-row"><small>Precio de simulación</small><strong>{money(m.price)}</strong></div><Button className="primary-button full-button" disabled={game.bankrupt||game.cash<m.price} onClick={()=>act(s=>buyPlane(s,m.id),`${m.name} incorporado a la flota.`)}>{game.cash<m.price?'Capital insuficiente':'Comprar avión'}<Plus/></Button><small className="aircraft-upkeep">Mantenimiento: {money(m.maintenance,false)} / trimestre</small></div></article>)}</div><p className="source-note">Asientos y alcances adaptados al juego a partir de <a href="https://www.airbus.com/en/products-services/commercial-aircraft/passenger-aircraft/a320-family" target="_blank" rel="noreferrer">Airbus</a>, <a href="https://www.embraer.com/continent-connectors-fly-e2/en/" target="_blank" rel="noreferrer">Embraer</a> y <a href="https://www.boeing.com/commercial/787" target="_blank" rel="noreferrer">Boeing</a>. Los precios, consumos y costos son parámetros de simulación.</p></>;
}
export function FinanceView({game,download,upload,newGame,report}:{game:Game;download:()=>void;upload:()=>void;newGame:()=>void;report:()=>void}){
 const t=totals(game),last=game.history.at(-1),recent=game.history.slice(-12),max=Math.max(1,...recent.map(r=>Math.abs(r.profit)));
 return <><div className="finance-grid"><section className="white-panel"><div className="section-heading"><div><p className="eyebrow">{quarterLabel(game.turn)} · PROYECCIÓN</p><h2>¿Cómo cerrará el trimestre?</h2></div><ChartNoAxesCombined/></div><div className="balance-lines">{[['Ingresos por pasajeros',money(t.revenue,false)],['Operación de rutas','− '+money(t.costs-OVERHEAD-t.idleMaintenance,false)],['Mantenimiento de aviones sin ruta','− '+money(t.idleMaintenance,false)],['Administración de la aerolínea','− '+money(OVERHEAD,false)]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}<div className="balance-total"><span>Resultado previsto</span><strong className={t.profit>=0?'positive':'negative'}>{money(t.profit,false)}</strong></div><div><span>Saldo después del cierre</span><strong>{money(game.cash+t.profit,false)}</strong></div></div><p className="field-hint">Las compras de aviones y aperturas de rutas se descuentan del capital al confirmar. El balance muestra la actividad operativa.</p></section>
 <section className="white-panel"><div className="section-heading"><div><p className="eyebrow">MERCADO SIMULADO</p><h2>La competencia no espera</h2></div><Building2/></div><p className="muted panel-copy">Tus rivales amplían sus redes con el tiempo y reducen la demanda disponible. Su evolución es simplificada.</p>{[...game.rivals,{name:game.name,routes:game.routes.length,score:game.reputation,color:'#73a77d'}].sort((a,b)=>b.routes-a.routes).map((r,i)=><div className="rival-row" key={i}><span className="ranking">0{i+1}</span><i style={{background:r.color}}/><div><strong>{r.name}</strong><small>Reputación {r.score}/100</small></div><span>{r.routes}<small>rutas</small></span></div>)}</section></div>
 <section className="white-panel history-panel"><div className="section-heading"><div><h2>El recorrido de tu aerolínea</h2><p>Historial de trimestres cerrados</p></div>{last&&<Button variant="outline" onClick={report}>Último informe <ArrowUpRight/></Button>}</div>{recent.length?<><div className="profit-chart" role="img" aria-label="Resultados de los últimos trimestres, detallados en la tabla siguiente.">{recent.map(r=><div key={r.turn} className="profit-column"><strong className={r.profit>=0?'positive':'negative'}>{money(r.profit)}</strong><div className="bar-zone"><div className={r.profit>=0?'profit-bar':'loss-bar'} style={{height:`${Math.max(3,Math.abs(r.profit)/max*100)}%`}}/></div><small>{quarterLabel(r.turn)}</small></div>)}</div><div className="table-wrap"><table className="routes-table"><thead><tr><th>TRIMESTRE</th><th>INGRESOS</th><th>COSTOS</th><th>RESULTADO</th><th>PASAJEROS</th></tr></thead><tbody>{[...game.history].reverse().map(r=><tr key={r.turn}><td>{quarterLabel(r.turn)}</td><td>{money(r.revenue)}</td><td>{money(r.costs)}</td><td className={r.profit>=0?'positive':'negative'}>{money(r.profit)}</td><td>{number(r.passengers)}</td></tr>)}</tbody></table></div></>:<div className="empty-state compact"><ChartNoAxesCombined/><h3>Todavía no cerraste tu primer trimestre.</h3><p>Avanzá el tiempo para ver los resultados de tus decisiones.</p></div>}</section>
 <section className="save-panel"><div><h3>Tu partida, a salvo</h3><p>Guardado automático en este navegador. Descargá una copia para llevarla a otro dispositivo.</p></div><div className="save-actions"><Button variant="outline" onClick={download}><ArrowDownToLine/> Descargar partida</Button><Button variant="outline" onClick={upload}><Upload/> Cargar partida</Button><Button variant="outline" onClick={newGame}><Plus/> Nueva aerolínea</Button></div></section></>;
}
