'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Compass, Plane, Plus, SlidersHorizontal, Fuel, TrendingUp, Globe2 } from 'lucide-react';
import { Button } from './ui/button';import { Input } from './ui/input';import { NativeSelect } from './ui/native-select';import { Progress } from './ui/progress';
import { WorldMap } from './world-map';import { CITIES, EVENTS, city, aircraft } from '@/lib/catalog';
import { configureRoute, closeRoute, routeEstimate, totals, recommendedFare, distance, maxFrequency, openingCost, quarterLabel, type Game, type Route } from '@/lib/engine';
import { money,number,percent } from '@/lib/format';import type { Act } from './game';
export function RoutesView({game,selected,select,act,goFleet,ready}:{game:Game;selected:string;select:(id:string)=>void;act:Act;goFleet:()=>void;ready:boolean}){
 const [plane,setPlane]=useState(''),[fare,setFare]=useState(300),[frequency,setFrequency]=useState(7);
 const route=game.routes.find(r=>r.to===selected);const available=game.fleet.filter(p=>!game.routes.some(r=>r.plane===p.id&&r.id!==route?.id));const current=game.fleet.find(p=>p.id===plane),model=current?aircraft(current.model):null;
 const km=distance(game.hub,selected),max=model?maxFrequency(game.hub,selected,model.id):7;
 useEffect(()=>{const r=game.routes.find(r=>r.to===selected);const p=game.fleet.find(p=>p.id===r?.plane)??game.fleet.find(p=>!game.routes.some(x=>x.plane===p.id));setPlane(p?.id??'');setFare(r?.fare??recommendedFare(game.hub,selected));setFrequency(r?.frequency??Math.min(7,p?maxFrequency(game.hub,selected,p.model):7));},[selected,game.hub,game.routes,game.fleet]);
 const issue=game.bankrupt?'La aerolínea está en quiebra.':selected===game.hub?'Elegí otro destino.':!model?'Necesitás un avión disponible.':km>model.range?'El destino supera el alcance del avión.':!Number.isFinite(fare)||fare<50||fare>2500?'La tarifa debe estar entre US$ 50 y US$ 2.500.':!Number.isInteger(frequency)||frequency<1||frequency>max?'Ajustá las frecuencias a las horas disponibles.':!route&&game.cash<openingCost(game.hub,selected)?'No tenés capital para abrir esta ruta.':null;
 const draft:Route={id:route?.id??'draft',to:selected,plane,fare,frequency};const estimate=!issue?routeEstimate(game,draft):null;
 const event=EVENTS[game.event],t=totals(game);
 return <><div className="operations-grid"><section className="map-panel"><div className="panel-heading"><h2>Tu próxima conexión</h2><span className="tag">MAPA MUNDIAL</span></div><WorldMap hub={game.hub} destinations={game.routes.map(r=>r.to)} selected={selected} onSelect={select}/><div className="map-note"><Compass size={19}/><p><strong>Comenzá cerca. Llegá más lejos.</strong> Los aviones regionales son una buena primera inversión.</p></div></section>
 <aside className="planner"><div className="planner-top"><p className="eyebrow">{route?'GESTIONAR RUTA':'EXPLORAR DESTINO'}</p><ArrowUpRight size={18}/></div><label className="sr-only" htmlFor="destination">Destino</label><NativeSelect id="destination" className="destination-select" value={selected} onChange={e=>select(e.target.value)}>{CITIES.filter(c=>c.id!==game.hub).map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</NativeSelect><div className="destination-summary"><span>{city(selected).country}</span><strong>{number(km)} km</strong></div><div className="route-endpoints"><span>{game.hub}<small>Base principal</small></span><span className="route-line"/><Plane size={18}/><span className="route-line"/><span>{selected}<small>{route?'Ruta activa':'Nuevo destino'}</small></span></div>
 <label className="field-label" htmlFor="route-plane">Avión asignado</label><NativeSelect id="route-plane" className="full-select" value={plane} onChange={e=>{setPlane(e.target.value);const p=game.fleet.find(p=>p.id===e.target.value);if(p)setFrequency(Math.min(frequency,maxFrequency(game.hub,selected,p.model)));}}><option value="">Seleccionar avión</option>{available.map(p=><option key={p.id} value={p.id}>{aircraft(p.model).name} · {p.id.toUpperCase()}</option>)}</NativeSelect>{model&&<small className={km>model.range?'field-hint negative':'field-hint'}>Alcance: {number(model.range)} km · {model.seats} asientos</small>}
 <div className="field-grid"><div><label className="field-label" htmlFor="fare">Tarifa · US$</label><Input id="fare" type="number" min={50} max={2500} value={Number.isNaN(fare)?'':fare} onChange={e=>setFare(e.target.value===''?NaN:Number(e.target.value))}/></div><div><label className="field-label" htmlFor="frequency">Idas y vueltas / sem.</label><Input id="frequency" type="number" min={1} max={max} step={1} value={Number.isNaN(frequency)?'':frequency} onChange={e=>setFrequency(e.target.value===''?NaN:Number(e.target.value))}/></div></div><p className="field-hint">Tarifa orientativa: {money(recommendedFare(game.hub,selected),false)} · Máx. {max} frecuencias</p>
 {estimate?<div className="forecast"><div><span>Ocupación estimada</span><strong>{percent(estimate.occupancy)}</strong></div><div><span>Margen de la ruta / trim.</span><strong className={estimate.profit>=0?'positive':'negative'}>{money(estimate.profit)}</strong></div><small>Incluye el mantenimiento del avión. Gastos de empresa aparte.</small></div>:<div className="planner-tip">{issue}{!model&&<button className="text-action" onClick={goFleet}>Ir al mercado de aviones <ArrowRight size={13}/></button>}</div>}
 <Button className="primary-button full-button" disabled={!!issue||!ready} onClick={()=>act(s=>configureRoute(s,{to:selected,plane,fare,frequency},route?.id),route?'Ruta actualizada.':'¡Nueva ruta inaugurada!')}>{route?'Guardar ajustes':'Inaugurar ruta'}<ArrowRight/></Button><small className="opening-cost">{route?'Los ajustes se aplican en este trimestre.':`Costo de apertura: ${money(openingCost(game.hub,selected),false)}`}</small>{route&&<button className="close-route" disabled={game.bankrupt} onClick={()=>act(s=>closeRoute(s,route.id),'Ruta cerrada. El avión vuelve a estar disponible.')}>Cerrar ruta y liberar avión</button>}</aside></div>
 <section className="routes-section"><div className="section-heading"><div><h2>Conexiones en operación <span>{game.routes.length}</span></h2><p>Proyección del trimestre actual · importes en dólares</p></div><Button variant="outline" onClick={()=>{const c=CITIES.find(c=>c.id!==game.hub&&!game.routes.some(r=>r.to===c.id));if(c)select(c.id);document.getElementById('destination')?.focus();}}><Plus/> Explorar ruta</Button></div>{game.routes.length?<div className="table-wrap"><table className="routes-table"><thead><tr><th>CONEXIÓN</th><th>AVIÓN</th><th>FRECUENCIA</th><th>OCUPACIÓN</th><th>RESULTADO</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{game.routes.map(r=>{const e=routeEstimate(game,r);return <tr key={r.id} className={selected===r.to?'selected-row':''}><td><div className="connection"><span className="connection-symbol"><Plane size={16}/></span><span><strong>{game.hub}<span className="route-arrow">→</span>{r.to}</strong><small>{city(r.to).name}</small></span></div></td><td>{aircraft(game.fleet.find(p=>p.id===r.plane)!.model).name}<small>{r.plane.toUpperCase()}</small></td><td>{r.frequency} <span className="muted">/ semana</span></td><td><div className="occupancy"><Progress value={e.occupancy*100} aria-label={`Ocupación de la ruta a ${city(r.to).name}`}/><span>{percent(e.occupancy)}</span></div></td><td className={e.profit>=0?'positive':'negative'}><strong>{money(e.profit)}</strong></td><td><Button variant="ghost" size="icon" aria-label={`Gestionar ruta a ${city(r.to).name}`} onClick={()=>{select(r.to);document.getElementById('destination')?.focus();}}><SlidersHorizontal/></Button></td></tr>;})}</tbody></table></div>:<div className="empty-state"><Globe2/><h3>Tu red empieza con una conexión.</h3><p>Comprá un avión y elegí un destino para inaugurar tu primera ruta.</p><Button variant="outline" onClick={goFleet}>Ver aviones <ArrowRight/></Button></div>}</section>
 <div className="bottom-grid"><section className="news-card"><div className="news-icon"><Fuel/></div><div><p className="eyebrow">EL MERCADO · {quarterLabel(game.turn)}</p><h3>{event.title}</h3><p>{event.text}</p></div><span className="tag">EVENTO SIMULADO</span></section><section className="quick-target"><TrendingUp/><div><strong>{percent(t.occupancy)} de ocupación</strong><p>Promedio previsto en toda tu red.</p></div></section></div></>;
}
